"use strict";
const favoriteAnimals = ['blowfish', 'capricorn', 'giraffe'];
console.log("Before: " + favoriteAnimals);
favoriteAnimals.push('turtle');
console.log('Adding Mauro\'s favorite animal \'turtle\': ' + favoriteAnimals);
favoriteAnimals.splice(1, 0, 'meerkat');
console.log('Adding Jim\'s favorite animal after \'blowfish\' and before \'capricorn\': ' + favoriteAnimals);
console.log('The array has a length of: ' + favoriteAnimals.length);
favoriteAnimals.splice(3, 1);
console.log('Deleting giraffe because Jason doesn\'t like it: ' + favoriteAnimals);
const found = favoriteAnimals.indexOf("meerkat");
console.log('The item you are looking for is at index: ' + found);
